USE [DCS-Shop]
GO

SELECT [InvoiceNo]
      ,[PartNo]
      ,[PartDesc]
      ,[JobNo]
      ,[QtyOrd]
      ,[QtyShipped]
      ,[QtyCancel]
      ,[Unit]
      ,[UnitPrice]
      ,[DiscPct]
      ,[TaxStatus]
      ,[SalesAcct]
      ,[CommPct]
      ,[GLAcct1]
      ,[SalesAmt1]
      ,[GLAcct2]
      ,[SalesAmt2]
      ,[GLAcct3]
      ,[SalesAmt3]
      ,[GLAcct4]
      ,[SalesAmt4]
      ,[GLAcct5]
      ,[SalesAmt5]
      ,[PONum]
      ,[DelTicketNo]
      ,[DelTicketDate]
      ,[WorkCode]
      ,[FOB]
      ,[ProdCode]
      ,[InvItemNo]
      ,[LineTotal]
      ,[NewDiscPct]
      ,[NewCommPct]
      ,[Revision]
      ,[ContactName]
      ,[BillingDet_ID]
      ,[AccountingID]
      ,[LastModDate]
      ,[LastModUser]
      ,[IsTaxable]
      ,[UnitPriceForeign]
      ,[SalesAmtForeign1]
      ,[SalesAmtForeign2]
      ,[SalesAmtForeign3]
      ,[SalesAmtForeign4]
      ,[SalesAmtForeign5]
      ,[LineTotalForeign]
  FROM [dbo].[BillingDet]

GO

