USE [DCS-Shop]
GO

SELECT [InvoiceNo]
      ,[PeriodNo]
      ,[DelTicketNo]
      ,[PymtStatus]
      ,[CustCode]
      ,[CustDesc]
      ,[InvDate]
      ,[PymtDate]
      ,[InvoiceTotal]
      ,[AmtPaidSoFar]
      ,[SalesTaxChgs]
      ,[CustCheckNo]
      ,[ARAcct]
      ,[DiscAcct]
      ,[TaxAcct]
      ,[SalesID]
      ,[WorkCode]
      ,[TaxCode]
      ,[TermsCode]
      ,[SAddr1]
      ,[SAddr2]
      ,[SCity]
      ,[SSt]
      ,[SZip]
      ,[ShipVia]
      ,[ShippingChgs]
      ,[FreightAcct]
      ,[EntBy]
      ,[DateEnt]
      ,[Notes]
      ,[InvPrinted]
      ,[CashDiscAmt]
      ,[DiscDate]
      ,[NetDueDate]
      ,[InvPosted]
      ,[ShipToName]
      ,[Territory]
      ,[Country]
      ,[GSTCode]
      ,[GSTChgs]
      ,[GSTAcct]
      ,[CurrencyCode]
      ,[ExchRate]
      ,[ProjPayDate]
      ,[IgnoreMinOrder]
      ,[Export]
      ,[ShipCode]
      ,[Exported]
      ,[Location]
      ,[ExportedToEDI]
      ,[Billing_ID]
      ,[AccountingID]
      ,[LastModDate]
      ,[LastModUser]
      ,[InvoiceTotalForeign]
      ,[AmtPaidSoFarForeign]
      ,[SalesTaxChgsForeign]
      ,[ShippingChgsForeign]
      ,[CashDiscAmtForeign]
      ,[GSTChgsForeign]
  FROM [dbo].[Billing]

GO

