USE [DCS-Shop]
GO

SELECT [OrderNo]
      ,[QuoteNo]
      ,[CustCode]
      ,[CustDesc]
      ,[PONum]
      ,[DateEnt]
      ,[EntBy]
      ,[SalesID]
      ,[TermsCode]
      ,[TaxCode]
      ,[PurchContact]
      ,[ShipAddr1]
      ,[ShipAddr2]
      ,[ShipCity]
      ,[ShipSt]
      ,[ShipZIP]
      ,[ShipVia]
      ,[Phone]
      ,[FAX]
      ,[NotesToCust]
      ,[WOPrinted]
      ,[AckPrinted]
      ,[JTPrinted]
      ,[OrderTotal]
      ,[Status]
      ,[Territory]
      ,[MainDueDate]
      ,[MainPriority]
      ,[ShipToName]
      ,[Country]
      ,[GSTCode]
      ,[CurrencyCode]
      ,[ExchRate]
      ,[DateEntLabel]
      ,[ShipCode]
      ,[User_Date1]
      ,[User_Date2]
      ,[User_Text1]
      ,[User_Text2]
      ,[User_Text3]
      ,[User_Text4]
      ,[User_Currency1]
      ,[User_Currency2]
      ,[User_Number1]
      ,[User_Number2]
      ,[User_Number3]
      ,[User_Number4]
      ,[User_Memo1]
      ,[Location]
      ,[Convert_Me]
      ,[Orders_ID]
      ,[LastModDate]
      ,[LastModUser]
      ,[OrderTotalForeign]
  FROM [dbo].[Orders]

GO

