USE [DCS-Shop]
GO

SELECT [QuoteNo]
      ,[Notes]
      ,[DefinedCust]
      ,[CustCode]
      ,[CustDesc]
      ,[Addr1]
      ,[Addr2]
      ,[City]
      ,[St]
      ,[Zip]
      ,[Phone]
      ,[FAX]
      ,[DateEnt]
      ,[EntBy]
      ,[InqNum]
      ,[TermsCode]
      ,[QuotedBy]
      ,[ContactName]
      ,[ShipVia]
      ,[SalesID]
      ,[TaxType]
      ,[Territory]
      ,[FollowUpDate]
      ,[ExpireDate]
      ,[Printed]
      ,[ShipToName]
      ,[Country]
      ,[GSTCode]
      ,[CurrencyCode]
      ,[ExchRate]
      ,[DateEntLabel]
      ,[ShipCode]
      ,[User_Date1]
      ,[User_Date2]
      ,[User_Text1]
      ,[User_Text2]
      ,[User_Text3]
      ,[User_Text4]
      ,[User_Currency1]
      ,[User_Currency2]
      ,[User_Number1]
      ,[User_Number2]
      ,[User_Number3]
      ,[User_Number4]
      ,[User_Memo1]
      ,[Location]
      ,[Quote_ID]
      ,[LastModDate]
      ,[LastModUser]
  FROM [dbo].[Quote]

GO

